### ISSUE TITLE
visible gutter bug

### ISSUE THREAD

**Issue by cnak** [codebar/mentoring.io#43]
### Visible gutter bug

There is a visible gutter on the right hand side of page(highlighted in yellow), which results in an unnecessary horizontal scrolling bar.
![gutter_bug](https://cloud.githubusercontent.com/assets/218601/8356667/99a81de6-1b4e-11e5-9993-b8ec3621c6e7.jpg)

Cedric

**Comment by despo** [comment]
:shipit:
